services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/:rw
    environment:
      POSTGRES_DB: "webserver"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/letsencrypt/:/etc/letsencrypt/:rw
      - ./data/certbot/www/:/var/www/certbot/:rw