version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "webserver"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: redis:7
    ports:
      - 6379:6379