version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "webserver"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: redis:7
    ports:
      - 6379:6379
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://admin:${POSTGRES_PASSWORD}@postgres:5432/webserver"
      REDIS_URL: "redis://redis:6379"
      RUST_LOG: "debug"
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis