name: Build and test code

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - 'src/**'
      - '.sqlx/**'
      - '.github/workflows/build.yaml'

env:
  SQLX_OFFLINE: true

jobs:
  build_and_test:
    name: Build and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build code
        run: cargo build --verbose
      
      - name: Test code
        run: cargo test --verbose